title: Easter Park
description: 温和的倔强派
url: http://easterfan.github.io
author: Easter
logo: assets/img/favicon.png
keywords: 
  - jekyll静态博客
  - 樊东方
  - easter
  - Java
  - Javaweb
  - 樊东方 easter
  - Bash
  - Vim

permalink: /:year/:month/:day/:title.html
paginate: 7
paginate_path: "page:num"
markdown: kramdown
markdown_ext:  md
excerpt_separator: "<!--more-->"
highlighter: rouge
lsi: false
exclude: ['README.md', '.*', 'bin/', 'Gemfile', 'node_modules', '*.log', 'package.json']
kramdown:
  input: GFM
  hard_wrap: false

ga: 'UA-121176712-2'
adsense:
disqus: 'easterpark'
twitter:
  username: harttleharttle

sass:
    style: compressed

collections:
  effective-cpp:
    output: true
    permalink: /:year/:month/:day/:title.html
  song:
    output: true
    permalink: /:year/:month/:day/:title.html
  vim-practice:
    output: true
    permalink: /:year/:month/:day/:title.html

defaults:
  -
    scope:
      path: "_drafts"
    values:
      layout: "blog"
  -
    scope:
      path: "_posts"
    values:
      layout: "blog"
  -
    scope:
      path: "_effective-cpp"
    values:
      layout: "blog"
  -
    scope:
      path: "_song"
    values:
      layout: "blog"
  -
    scope:
      path: "_vim-practice"
    values:
      layout: "blog"

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
